const strings = {
  app_name: 'Asara',
  your_number: "What's your number ?",
  request_otp: 'REQUEST OTP',
  whatsappText: 'Continue with Whatsapp',
  _91: '+91',
  verify_phone_number: 'Verify Phone number',
  otp_code: 'Enter OTP code sent to your number',
  privacy_policy_text: 'We take your privacy policy very seriously. ',
  agreeing_text: 'By agreeing to move forward, ',
  agree_to: 'you agree to ',
  terms_of_use: 'Terms of Use',
  and: ' and ',
  privacy_policy: 'Privacy Policy.',
  submit: 'Submit',
  asara_chat_text:
    'Hello , I am Asara. I will be your new friend. I am trained to help senior citizens. I would like to know more about you. Let’s start this amazing journey by knowing more about you.',
  interests_hobbies: 'Select your interests/ hobbies?',
  yes: 'Yes',
  no: 'No',
  dont_share: "Don't want to share",
  dont_join_community: "Don't want to join any community",
  select_communities: 'Select Group',
  fullname: 'Full Name',
  select_year: 'Select Year',
  select_city: 'Select City',
  select_person: 'Select Person',
  tap_here: 'Tap here to select',
  select_friends: 'Select Friends',
  select_community: 'Select Group',
  select_locaion: 'Select Location',
};

export default strings;
