//loaders
export const AUTH_ENABLE_LOADER = 'AUTH_ENABLE_LOADER';
export const AUTH_DISABLE_LOADER = 'AUTH_DISABLE_LOADER';

// AUTH
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_RESPONSE = 'AUTH_RESPONSE';
export const AUTH_FAILED = 'AUTH_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const SET_DID_TRY_AL = 'SET_DID_TRY_AL';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS_RESPONSE = 'SIGNUP_SUCCESS_RESPONSE';
export const HASH = 'HASH';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

// OTP
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_RESPONSE = 'OTP_RESPONSE';
export const OTP_CHALLENGE_REQUEST = 'OTP_CHALLENGE_REQUEST';
export const OTP_FAILED = 'OTP_FAILED';

// OnBoarding
export const ONBOARDING_GET_LATEST_REQUEST = 'ONBOARDING_GET_LATEST_REQUEST';
export const ONBOARDING_GET_LATEST_RESPONSE = 'ONBOARDING_GET_LATEST_RESPONSE';
export const ONBOARDING_GET_LATEST_FAILED = 'ONBOARDING_GET_LATEST_FAILED';
export const ONBOARDING_GET_COMMUNITY = 'ONBOARDING_GET_COMMUNITY';
export const ONBOARDING_UPDATE_USER_FETCHED_LIST = 'ONBOARDING_UPDATE_USER_FETCHED_LIST';

export const ONBOARDING_UPDATE_QUESTION_ANSWER_LIST =
  'ONBOARDING_UPDATE_QUESTION_ANSWER_LIST';
export const ONBOARDING_RESET_LIST = 'ONBOARDING_RESET_LIST';
export const ONBOARDING_SELECTED_HOBBIES = 'ONBOARDING_SELECTED_HOBBIES';
export const ONBOARDING_SELECTED_DIESES = 'ONBOARDING_SELECTED_DIESES';
export const ONBOARDING_SELECTED_COMMUNITIES =
  'ONBOARDING_SELECTED_COMMUNITIES';
export const ONBOARDING_BACK = 'ONBOARDING_BACK';
export const ONBOARDING_COMPLETE = 'ONBOARDING_COMPLETE';
export const ONBOARDING_SKIP = 'ONBOARDING_SKIP';
export const ONBOARDING_SAVE = 'ONBOARDING_SAVE';

export const ONBOARDING_UPDATE_USER_ANSWER_LIST = 'ONBOARDING_UPDATE_USER_ANSWER_LIST';





export const GET_COMMUNITY = 'GET_COMMUNITY';
export const GET_COMMUNITY2 = 'GET_COMMUNITY2';
export const GET_USER_COMMUNITY = 'GET_USER_COMMUNITY';
export const SET_USER_COMMUNITY = 'SET_USER_COMMUNITY';


export const UPDATE_TAG_FRIENDS = 'UPDATE_TAG_FRIENDS';
export const UPDATE_TAG_COMMUNITIES = 'UPDATE_TAG_COMMUNITIES';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_POST_INITIALS = 'UPDATE_POST_INITIALS';
export const POST_COMPLETED = 'POST_COMPLETED';
export const UPDATE_POST_RESET = 'UPDATE_POST_RESET';


export const CREATE_USER_POST = 'CREATE_USER_POST';
export const UPDATE_USER_POST = 'UPDATE_USER_POST';
export const GET_USER_POST = 'GET_USER_POST';
export const GET_USER_POST_FULL = 'GET_USER_POST_FULL';


export const GET_USER_POST_RESPONSE = 'GET_USER_POST_RESPONSE';
export const RESET_USER_POST = 'RESET_USER_POST';
export const GET_USER_CITY = 'GET_USER_CITY';
export const SET_USER_CITY = 'SET_USER_CITY';
export const GET_USER_FRIENDS = 'GET_USER_FRIENDS';
export const SET_USER_FRIEND = 'SET_USER_FRIEND';

export const CREATE_USER_POST_IMAGE = 'CREATE_USER_POST_IMAGE';
export const CREATE_USER_POST_VIDEO = 'CREATE_USER_POST_VIDEO';

export const GET_POST_COMMENT = 'GET_POST_COMMENT';
export const SET_POST_COMMENT = 'SET_POST_COMMENT';
export const SAVE_POST_COMMENT = 'SAVE_POST_COMMENT';

export const SET_POST_COMMENT_SINGLE = 'SET_POST_COMMENT_SINGLE';

export const COMMENT_REFRESH = 'COMMENT_REFRESH';
export const SAVE_POST_ACTIONS = 'SAVE_POST_ACTIONS';
export const DOT_POST_ACTIONS = 'DOT_POST_ACTIONS';


export const REMOVE_POST_BY_ID = 'REMOVE_POST_BY_ID';
export const UPDATE_POST_COMMENT = 'UPDATE_POST_COMMENT';
export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE';
export const UPDATE_POST_HEART = 'UPDATE_POST_HEART';

export const GET_POST_COMMENT_DETAILS = 'GET_POST_COMMENT_DETAILS';

export const SET_POST_COMMENT_DETAILS = 'SET_POST_COMMENT_DETAILS';

export const RESET_POST_COMMENT_DETAILS = 'RESET_POST_COMMENT_DETAILS';
export const COMMUNITY_CATEGORY = 'COMMUNITY_CATEGORY';
export const SET_COMMUNITY_CATEGORY = 'SET_COMMUNITY_CATEGORY';

export const CREATE_COMMUNITY = 'CREATE_COMMUNITY';
export const COMMUNITY_TAGS = 'COMMUNITY_TAGS';
export const SET_COMMUNITY_HASH = 'SET_COMMUNITY_HASH';
export const GET_USER_POST_COMMUNITY = 'GET_USER_POST_COMMUNITY';
export const GET_USER_POST_RESPONSE_COMMUNITY = 'GET_USER_POST_RESPONSE_COMMUNITY';
export const UPDATE_POST_TYPE = 'UPDATE_POST_TYPE';
export const RESET_POST_TYPE = 'RESET_POST_TYPE';
export const UPDATE_USER_POST_COMMUNITY = 'UPDATE_USER_POST_COMMUNITY';

export const RESET_USER_POST_RESPONSE_COMMUNITY = 'RESET_USER_POST_RESPONSE_COMMUNITY';
export const INVITE_BRANCH_USER_ID = 'INVITE_BRANCH_USER_ID';

export const SET_INVITE_FRIEND = 'SET_INVITE_FRIEND';

export const DOT_POST_ACTIONS_COMMUNITY = 'DOT_POST_ACTIONS_COMMUNITY';

export const REMINDER_CATEGORY_SET = 'REMINDER_CATEGORY_SET';
export const REMINDER_CATEGORY_GET = 'REMINDER_CATEGORY_GET';

export const SET_MEDICINE_FORM = 'SET_MEDICINE_FORM';
export const GET_MEDICINE_FORM = 'GET_MEDICINE_FORM';

export const GET_MEDICINE_NAME = 'GET_MEDICINE_NAME';
export const SET_MEDICINE_NAME = 'SET_MEDICINE_NAME';

export const SET_MEDICINE_FOR = 'SET_MEDICINE_FOR';
export const GET_MEDICINE_FOR = 'GET_MEDICINE_FOR';

export const SET_MEDICINE_REMINDER = 'SET_MEDICINE_REMINDER';
export const SET_MEDICINE_FORM_COMPLETE = 'SET_MEDICINE_FORM_COMPLETE';
export const RESET_MEDICINE_REMINDER_FORM = 'RESET_MEDICINE_REMINDER_FORM';

export const SET_REMINDER = 'SET_REMINDER';

export const SET_REMINDER_FORM_COMPLETE = 'SET_REMINDER_FORM_COMPLETE';
export const RESET_REMINDER_FORM_COMPLETE = 'RESET_REMINDER_FORM_COMPLETE';
export const GET_COMMUNITY_MODERRATION_DATA = 'GET_COMMUNITY_MODERRATION_DATA';
export const SET_COMMUNITY_MODERRATION_DATA = 'SET_COMMUNITY_MODERRATION_DATA';
export const SEND_USER_TOKEN = 'SEND_USER_TOKEN';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const RESET_NOTIFICATION_COUNT = 'RESET_NOTIFICATION_COUNT';

export const DOCTOR_UPCOMMING_SCHEDULE = 'DOCTOR_UPCOMMING_SCHEDULE';
export const DOCTOR_TOP_SPECIALIST = 'DOCTOR_TOP_SPECIALIST';
export const DOCTOR_POPULAT_HEALTH_ISSUE = 'DOCTOR_POPULAT_HEALTH_ISSUE';
export const DOCTOR_YOUR_HEALTH_ISSUE = 'DOCTOR_YOUR_HEALTH_ISSUE';
export const DOCTOR_FAMOUS_DOCTOR = 'DOCTOR_FAMOUS_DOCTOR';
export const DOCTOR_NEAR_YOU = 'DOCTOR_NEAR_YOU';

export const SET_DOCTOR_UPCOMMING_SCHEDULE = 'SET_DOCTOR_UPCOMMING_SCHEDULE';
export const SET_DOCTOR_TOP_SPECIALIST = 'SET_DOCTOR_TOP_SPECIALIST';
export const RESET_DOCTOR_TOP_SPECIALIST = 'RESET_DOCTOR_TOP_SPECIALIST';


export const SET_DOCTOR_POPULAT_HEALTH_ISSUE = 'SET_DOCTOR_POPULAT_HEALTH_ISSUE';
export const SET_DOCTOR_YOUR_HEALTH_ISSUE = 'SET_DOCTOR_YOUR_HEALTH_ISSUE';
export const SET_DOCTOR_FAMOUS_DOCTOR = 'SET_DOCTOR_FAMOUS_DOCTOR';
export const SET_DOCTOR_NEAR_YOU = 'SET_DOCTOR_NEAR_YOU';
export const GET_DOCTOR_BY_SPECIALITY = 'GET_DOCTOR_BY_SPECIALITY';
export const SET_DOCTOR_BY_SPECIALITY = 'SET_DOCTOR_BY_SPECIALITY';

export const GET_DOCTOR_SCHEDULE = 'GET_DOCTOR_SCHEDULE';
export const SET_DOCTOR_SCHEDULE = 'SET_DOCTOR_SCHEDULE';

export const CREATE_DOCTOR_BOOKING_2 = 'CREATE_DOCTOR_BOOKING_2';
export const SET_UPCOMING_SCHEDULE = 'SET_UPCOMING_SCHEDULE';

export const RESET_UPCOMING_SCHEDULE = 'RESET_UPCOMING_SCHEDULE';

export const RESET_DOCTOR_SCHEDULE = 'RESET_DOCTOR_SCHEDULE';
export const GET_DOCTOR_DETAIL = 'GET_DOCTOR_DETAIL';
export const SET_DOCTOR_DETAIL = 'SET_DOCTOR_DETAIL';
export const GET_USER_ALL_SCHEDULE = 'GET_USER_ALL_SCHEDULE';
export const SET_USER_ALL_SCHEDULE = 'SET_USER_ALL_SCHEDULE';
export const ONBOARDING_TRIGGER_SAVE = 'ONBOARDING_TRIGGER_SAVE';
export const SET_SAVE_PROGRESS = 'SET_SAVE_PROGRESS'; 
export const SET_USER_MEDICAL_DATA = 'SET_USER_MEDICAL_DATA';
export const SET_USER_MEDICAL_DASHBOARD = 'SET_USER_MEDICAL_DASHBOARD';


export const COMMUNITY_NAME_CHANGE = 'COMMUNITY_NAME_CHANGE';
export const COMMUNITY_PHOTO_CHANGE = 'COMMUNITY_PHOTO_CHANGE';
export const POST_ICON_DETAILS = 'POST_ICON_DETAILS';
export const GET_USER_POST_RESPONSE_ALL = 'GET_USER_POST_RESPONSE_ALL';
export const UPDATE_USER_LIKE = 'UPDATE_USER_LIKE';

export const SET_CHANNEL_DATA = 'SET_CHANNEL_DATA';
export const GET_CHANNEL_DATA = 'GET_CHANNEL_DATA';
export const GET_BANNER_DATA = 'GET_BANNER_DATA';
export const SET_BANNER_DATA = 'SET_BANNER_DATA';

export const SET_TOP_MENU_CLICKEDITEM = 'SET_TOP_MENU_CLICKEDITEM';

export const GET_CITY = 'GET_CITY';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';

export const GET_SHOP_CATEGORY = 'GET_SHOP_CATEGORY';

export const SET_SHOP_CATEGORY = 'SET_SHOP_CATEGORY';
export const GET_SHOP_CATEGORY_DATA = 'GET_SHOP_CATEGORY_DATA';
export const SET_SHOP_CATEGORY_DATA = 'SET_SHOP_CATEGORY_DATA'; 
export const SET_SHOP_CATEGORY_CHILD_ACTIVE = 'SET_SHOP_CATEGORY_CHILD_ACTIVE';


export const SET_SHOP_DETAIL_DATA = 'SET_SHOP_DETAIL_DATA'; 
export const GET_SHOP_DETAIL_DATA = 'GET_SHOP_DETAIL_DATA'; 
export const SET_SHOP_DETAIL_RESET = 'SET_SHOP_DETAIL_RESET';


export const GET_SHOP_CHILD_CATEGORY_DATA = 'GET_SHOP_CHILD_CATEGORY_DATA';
export const SET_SHOP_CHILD_CATEGORY_DATA = 'SET_SHOP_CHILD_CATEGORY_DATA';

export const GET_SHOP_CHILD2_CATEGORY_DATA = 'GET_SHOP_CHILD2_CATEGORY_DATA';
export const SET_SHOP_CHILD2_CATEGORY_DATA = 'SET_SHOP_CHILD2_CATEGORY_DATA';

export const SAVE_USER_MEDICAL_DATA = 'SAVE_USER_MEDICAL_DATA';
export const GET_USER_MEDICAL_DATA = 'GET_USER_MEDICAL_DATA'; 
export const GET_USER_MEDICAL_DASHBOARD = 'GET_USER_MEDICAL_DASHBOARD';


export const GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS';
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';

export const GET_SERVICES_CATEGORY = 'GET_SERVICES_CATEGORY';
export const SET_SERVICE_CATEGORY = 'SET_SERVICE_CATEGORY';

export const GET_SERVICES_CHILD2_CATEGORY_DATA = 'GET_SERVICES_CHILD2_CATEGORY_DATA';
export const SET_SERVICES_CHILD2_CATEGORY_DATA = 'SET_SERVICES_CHILD2_CATEGORY_DATA';


export const GET_SERVICES_DETAIL = 'GET_SERVICES_DETAIL';
export const SET_SERVICES_DETAIL = 'SET_SERVICES_DETAIL';
export const RESET_SERVICES_DETAIL = 'RESET_SERVICES_DETAIL';
export const GET_SERVICE_OPTIONS = 'GET_SERVICE_OPTIONS';
export const SET_SERVICE_OPTIONS = 'SET_SERVICE_OPTIONS';

export const SET_CATEGORY_AND_REMINDER_UPDATE = 'SET_CATEGORY_AND_REMINDER_UPDATE';


